<?php

namespace BFOS\PagamentoDigitalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RespostaPagamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespostaPagamentoRepository extends EntityRepository
{
    public function persist(RespostaPagamento $resposta_pagamento){
        $this->_em->persist($resposta_pagamento);
    }

    public function flush(){
        $this->_em->flush();
    }
}