<?php

namespace BFOS\PagamentoDigitalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransacaoRepository extends EntityRepository
{
    public function persist(Transacao $transacao){
        $this->_em->persist($transacao);
    }

    public function flush(){
        $this->_em->flush();
    }
}